config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer

  root to: 'questions#ask'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    if @question[-1] == '?'
      @reply_question = 'Silly question, get dressed and go to work!'
    elsif @question == 'I am going to work'
      @reply_great = 'Great!'
    else
      @reply_rest = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1 class="text-center">STUPID COACHING</h1>


<div class="container user">
  <p><%= @question %></p>
  <p><em>- Your question</em></p>
</div>

<div class="container coach">
  <p><%= @reply_question %></p>
  <p><%= @reply_great %></p>
  <p><%= @reply_rest %></p>
  <p><em>- Your coach</em></p>
</div>

<div class="container link">
  <%= link_to "Ask more questions", ask_path %>
</div>

app/views/questions/ask.html.erb
<h1 class="text-center">STUPID COACHING</h1>



<div class="container">
  <form action="/answer">
    <p id="form-instruction" class="text-center">Ask your coach anything:</p>
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="Say something to your coach" name="question">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" id="button-addon2">Ask</button>
      </div>
    </div>
  </form>
</div>